#############################################################################
# Generated by PAGE version 4.24.1
#  in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}



if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}


proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 969x494+179+94
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 749
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra43 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 475 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 945 
    vTcl:DefineAlias "$top.fra43" "main_frame" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra43
    ttk::combobox $site_3_0.tCo46 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo46" "instance_combo" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab49 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text X 
    vTcl:DefineAlias "$site_3_0.lab49" "x_label" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab50 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Y 
    vTcl:DefineAlias "$site_3_0.lab50" "y_label" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab51 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Z 
    vTcl:DefineAlias "$site_3_0.lab51" "z_label" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_3_0.spi52 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkTextFont -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable spinbox -to 100.0 
    vTcl:DefineAlias "$site_3_0.spi52" "x_spin" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_3_0.spi53 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkTextFont -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable spinbox -to 100.0 
    vTcl:DefineAlias "$site_3_0.spi53" "y_spin" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_3_0.spi54 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkTextFont -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable spinbox -to 100.0 
    vTcl:DefineAlias "$site_3_0.spi54" "z_spin" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Roll 
    vTcl:DefineAlias "$site_3_0.lab55" "roll_label" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab56 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Yaw 
    vTcl:DefineAlias "$site_3_0.lab56" "yaw_label" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab57 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Pitch 
    vTcl:DefineAlias "$site_3_0.lab57" "pitch_label" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_3_0.spi58 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkTextFont -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable spinbox -to 100.0 
    vTcl:DefineAlias "$site_3_0.spi58" "pitch_spin" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_3_0.spi59 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkTextFont -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable spinbox -to 100.0 
    vTcl:DefineAlias "$site_3_0.spi59" "yaw_spin" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_3_0.spi60 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkTextFont -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable spinbox -to 100.0 
    vTcl:DefineAlias "$site_3_0.spi60" "roll_spin" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but61 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Add instance} 
    vTcl:DefineAlias "$site_3_0.but61" "add_instance_button" vTcl:WidgetProc "Toplevel1" 1
    canvas $site_3_0.can63 \
        -background {#d9d9d9} -borderwidth 2 -closeenough 1.0 -height 203 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground {#c4c4c4} \
        -selectforeground black -width 283 
    vTcl:DefineAlias "$site_3_0.can63" "blueprint_canvas" vTcl:WidgetProc "Toplevel1" 1
    listbox $site_3_0.lis68 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -height 362 -highlightbackground {#d9d9d9} \
        -highlightcolor black -selectbackground {#c4c4c4} \
        -selectforeground black -width 624 
    .top42.fra43.lis68 configure -font "TkFixedFont"
    .top42.fra43.lis68 insert end text
    vTcl:DefineAlias "$site_3_0.lis68" "instance_list" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but69 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} -height 24 \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Remove instance} -width 110 
    vTcl:DefineAlias "$site_3_0.but69" "remove_instance_button" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but70 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Load project} -width 110 
    vTcl:DefineAlias "$site_3_0.but70" "load_project_button" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but71 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Save project} -width 110 
    vTcl:DefineAlias "$site_3_0.but71" "save_project_button" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but72 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Generate XML} -width 110 
    vTcl:DefineAlias "$site_3_0.but72" "generate_xml_button" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.tCo46 \
        -in $site_3_0 -x 40 -y 70 -width 233 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 30 -y 330 -width 54 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 30 -y 360 -width 54 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 30 -y 390 -width 54 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi52 \
        -in $site_3_0 -x 80 -y 330 -width 45 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi53 \
        -in $site_3_0 -x 80 -y 360 -width 45 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.spi54 \
        -in $site_3_0 -x 80 -y 390 -width 45 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 140 -y 390 -width 34 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab56 \
        -in $site_3_0 -x 140 -y 360 -width 34 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 140 -y 330 -width 34 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.spi58 \
        -in $site_3_0 -x 180 -y 330 -width 45 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.spi59 \
        -in $site_3_0 -x 180 -y 360 -width 45 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.spi60 \
        -in $site_3_0 -x 180 -y 390 -width 45 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but61 \
        -in $site_3_0 -x 80 -y 440 -width 123 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.can63 \
        -in $site_3_0 -x 10 -y 100 -width 283 -height 203 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lis68 \
        -in $site_3_0 -x 311 -y 61 -width 624 -relwidth 0 -height 362 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but69 \
        -in $site_3_0 -x 570 -y 440 -width 110 -height 24 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but70 \
        -in $site_3_0 -x 20 -y 20 -width 110 -height 24 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but71 \
        -in $site_3_0 -x 170 -y 20 -width 110 -height 24 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but72 \
        -in $site_3_0 -x 310 -y 20 -width 110 -height 24 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra43 \
        -in $top -x 10 -y 10 -width 945 -relwidth 0 -height 475 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

